name: Global Martkets Update

on:
  schedule:
    - cron: '5 21 * * 1-5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        env:
          EIKON_API_KEY: ${{secrets.EIKON_API_KEY}}
          EIKON_LOGIN_ID: ${{secrets.EIKON_LOGIN_ID}}
          EIKON_LOGIN_PASS: ${{secrets.EIKON_LOGIN_PASS}}
          EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}
          EMAIL_RECIPIENT1: ${{secrets.EMAIL_RECIPIENT1}}
          EMAIL_RECIPIENT2: ${{secrets.EMAIL_RECIPIENT2}}
          EMAIL_RECIPIENT3: ${{secrets.EMAIL_RECIPIENT3}}
          EMAIL_RECIPIENT4: ${{secrets.EMAIL_RECIPIENT4}}
          EMAIL_RECIPIENT5: ${{secrets.EMAIL_RECIPIENT5}}
          EMAIL_RECIPIENT6: ${{secrets.EMAIL_RECIPIENT6}}
          EMAIL_RECIPIENT7: ${{secrets.EMAIL_RECIPIENT7}}
          EMAIL_RECIPIENT8: ${{secrets.EMAIL_RECIPIENT8}}
          EMAIL_RECIPIENT9: ${{secrets.EMAIL_RECIPIENT9}}
          EMAIL_RECIPIENT10: ${{secrets.EMAIL_RECIPIENT10}}
          EMAIL_RECIPIENT11: ${{secrets.EMAIL_RECIPIENT11}}
          EMAIL_RECIPIENT12: ${{secrets.EMAIL_RECIPIENT12}}
          EMAIL_RECIPIENT13: ${{secrets.EMAIL_RECIPIENT13}}
          EMAIL_RECIPIENT14: ${{secrets.EMAIL_RECIPIENT14}}
          EMAIL_RECIPIENT15: ${{secrets.EMAIL_RECIPIENT15}}
          EMAIL_RECIPIENT16: ${{secrets.EMAIL_RECIPIENT16}}
          EMAIL_RECIPIENT17: ${{secrets.EMAIL_RECIPIENT17}}
          EMAIL_RECIPIENT18: ${{secrets.EMAIL_RECIPIENT18}}
          EMAIL_RECIPIENT19: ${{secrets.EMAIL_RECIPIENT19}}
          EMAIL_RECIPIENT20: ${{secrets.EMAIL_RECIPIENT20}}
          MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}
        run: python global-markets.py
      - name: Commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git add .
          git commit -m 'Update csv file'
          git push origin main
